spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bookingdb_qa
    username: prashant
    password: "{cipher}f27e88684f172b532640f272fcf3c015d83a9c14f19bab2336ea10ce258dec06"
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
build:
  version: "2.0"

booking:
  message: "Welcome to InfyGo Booking Related Service"
  contactDetails:
    name: "Swapnil Mishra - QA LEad"
    email: "swapnil@infygo.com"
  onCallSupport:
    - (91) 1234567891
    - (91) 0987654322
