spring:
  datasource:
    url: jdbc:mysql://localhost:3306/flightdb_qa
    username: prashant
    password: admin123@
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

build:
  version: "2.0"

flight:
  message: "Welcome to InfyGo Flight Related Service"
  contactDetails:
    name: "Swapnil Mishra - QA LEad"
    email: "swapnil@infygo.com"
  onCallSupport:
    - (91) 1234567891
    - (91) 0987654322
